### PR TITLE
Merging hestia fork

### PR DESCRIPTION
**Pull request by flexjoly**
Hi @ReimuHakurei, @jaapmarcus,

Just created this pull request from the fork of Jaap,

Would this work?

Greetz, flexJoly

### CODE REVIEW

**Comment by flexjoly** [comment]
uh.... this seems to be a lot of changes ....
Maybe not safe?

And 'hestia' needs to be removed 😛

**Comment by jaapmarcus** [comment]
Drop this commit (https://github.com/phpPgAdmin2/phpPgAdmin/pull/4/commits/aa2d1bf4613ac0d8a72ecc023d0dfc6ca3306dae) 

ADOdb is include via composer instead copied into the repo source code. As it is now loaded from composer you don't need it any more...

The release drafter will release a new version after a new release has been created and will also download composer packages...

**Comment by ReimuHakurei** [comment]
What issues are fixed in this fork that aren't already fixed?

There are a lot of alternative patches that all fix the same bunch of issues in phpPgAdmin -- trying to merge them all on top of each other is just begging for conflicts.

If there are any fixes in this fork that aren't already fixed, the proper solution there would be to cherry-pick the specific commits in question.

**Comment by jaapmarcus** [comment]
Except for the font-size. The other major change is moving ADOdb to composer 

https://github.com/phpPgAdmin2/phpPgAdmin/pull/4/commits/25bc6b6c2bac89f3b2a7603696774926d1c20e90

**Comment by flexjoly** [comment]
@jaapmarcus Can you make a new pull-request or proposal for the changes in your branche that you would like to see here?

Thanks in advance!

**Pull request closed without merging**
